--liquebase farmatted sql

--changeset ekaterina:1
CREATE TEBLE IF NOT EXIST notification_tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    notification_date_time TIMESTAMP NOT NULL
);
